services:

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres_docker
      - POSTGRES_PASSWORD=90807010
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - data_pg:/var/lib/postgresql/data

volumes:
  data_pg:
